### ISSUE TITLE
cryptoexample.c com erro de biblioteca, código errado

### ISSUE THREAD

**Issue by iaglourenco** [iaglourenco/CryptoModule#1]
[cryptoexample.c](https://github.com/iaglourenco/CryptoModule/blob/master/cryptoexample.c) com erro de biblioteca 

```
cryptoexample.c:12:10: fatal error: asm/scatterlist.h: No such file or directory
           #include <asm/scatterlist.h>
```

**Comment by iaglourenco** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implementação dos exemplos fornecidos](https://trello.com/c/ioHtsApI/12-implementa%C3%A7%C3%A3o-dos-exemplos-fornecidos)

**Comment by iaglourenco** [comment]
Scatterlist.h encontrado a23f25c2cbe8a0d6bd271465b37b782589ec30a4

O erro de dependência resolvido, mas o código ainda continua errado, vamos ter que mandar e-mail para o Edmar ou tentar descobrir com outras pessoas.

Já procurei de tudo

**Comment by tomasmartinolli** [comment]
Resolvido, cryptoexample estava defasada e somente funcionava no kernel 2.6, eh necessario usar o codigo listado abaixo em conjunto com a ideia da cryptoexample.c

https://www.kernel.org/doc/html/v4.14/crypto/api-samples.html#code-example-for-symmetric-key-cipher-operation

**Comment by iaglourenco** [comment]
RESOLVIDO
O código da cryptoexample.c esta defasado, e só funciona no kernel 2.6, a API de criptografia mudou, é necessário usar os códigos de exemplo do link abaixo para fazer a criptografia.Porém nesse exemplo o código não está implementado para funcionar com um módulo, é necessario adaptar.

[Linux Kernel Crypto API - Code Examples](https://www.kernel.org/doc/html/v4.14/crypto/api-samples.html#code-example-for-symmetric-key-cipher-operation)
