### ISSUE TITLE
Anotações importantes

### ISSUE THREAD

**Issue by iaglourenco** [iaglourenco/CryptoModule#3]
`grep -r nome_da_função *` dentro da pasta build dos headers para achar os includes necessarios

**Comment by fabioirokawa** [comment]
`crypto_alloc_skcipher("cbc-aes-aesni",0,0)` linha do código da criptografia
`crypto_alloc_skcipher("cbc-aes",0,0)` || `cbc(aes)` linha atualizada com a criptografia a ser usada no projeto

**Comment by fabioirokawa** [comment]
`find -L . -iname scatter*` procura (`find`) pelos links simbólicos (`-L`) na pasta que estou no momento (`.`) todos os arquivos (`*`) com "_scatter_" no nome

**Comment by fabioirokawa** [comment]
`grep` procura algo no conteudo do arquivo
`find` procura nome do arquivo

**Comment by iaglourenco** [comment]
[Code Example For Symmetric Key Cipher Operation
](https://www.kernel.org/doc/html/v4.12/crypto/api-samples.html#code-example-for-symmetric-key-cipher-operation)

[Como o “scatterlist” funciona no linux?](https://stackoverflow.com/questions/29270447/how-does-scatterlist-works-in-linux)

[Advanced Encryption Standard (AES) Wikipedia](https://pt.wikipedia.org/wiki/Advanced_Encryption_Standard)

[Animação do Rijndael](http://blog.ultrassecreto.com/wp-content/uploads/2009/06/projetofinal.html)

**Comment by iaglourenco** [comment]
Nao vamos usar funçoes de callback
Callback é criptografia assincrona, ou seja, com o callback a gente chama a função de criptografia e deixa ela executando em pararelo, e quando ela terminar ela avisa. Portanto **NÃO** usaremos callback functions

**Comment by iaglourenco** [comment]
> `crypto_alloc_skcipher("cbc-aes-aesni",0,0)` linha do código da criptografia
> `crypto_alloc_skcipher("cbc-aes",0,0)` || `cbc(aes)` linha atualizada com a criptografia a ser usada no projeto

[Man pages](https://manpages.debian.org/jessie-backports/linux-manual-4.8/crypto_alloc_skcipher.9.en.html)

**Comment by iaglourenco** [comment]
[Man pages](https://manpages.debian.org/testing/linux-manual-4.8/skcipher_request_alloc.9)

**Comment by iaglourenco** [comment]
Temos 3 tipos de AES:

AES256
AES192
AES128

o numero indica o tamanho requerido para a chave (em bits), que ficam,convertidas para bytes, 32,24 e 16 bytes respectivamente
